server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:h2:mem:db;MODE=MySQL;DATABASE_TO_LOWER=TRUE
  flyway:
    enabled: true
    user: root
    password: test
    locations: classpath:/db/migration
