name: Release

on:
  workflow_dispatch:
    inputs:
      semver:
        type: choice
        description: Semantic version
        options:
          - major
          - minor
          - patch
        required: false
        default: minor

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump up maven Version
        id: bump
        uses: nnichols/maven-version-bump-action@v3
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          pom-path: ${{ github.workspace }}/pom.xml
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          DEFAULT_BUMP: ${{ github.event.input.semver }}
          INITIAL_VERSION: 0.0.0
          WITH_V: true
          RELEASE_BRANCHES: main
